### ISSUE TITLE
[feature request] Add Pytorch

### ISSUE THREAD

**Issue by Wulfsta** [nixos-rocm/nixos-rocm#14]
I was wondering if adding an expression for PyTorch for Python 3 would be out of scope for this overlay? It seems to me as if it is appropriate, due to the ROCm Software Platform port that exists and the inclusion of TensorFlow. Instructions to compile it for Python 3 can be found [here](https://github.com/ROCmSoftwarePlatform/pytorch/issues/337#issuecomment-467220107).

**Comment by Wulfsta** [comment]
[Additional, more up to date information](https://github.com/ROCmSoftwarePlatform/pytorch/issues/373#issuecomment-473382643).

**Comment by acowley** [comment]
I think it belongs here, too. I’d welcome a PR!

**Comment by Wulfsta** [comment]
Sounds good, I'll see if I can get it running!

**Comment by acowley** [comment]
I've added `rocSPARSE` to the [2.4.x](https://github.com/nixos-rocm/nixos-rocm/tree/2.4.x) branch. Hopefully this gets us close to getting `pytorch` up and running!

**Comment by acowley** [comment]
I got packaging for `pytorch` working with ROCm 2.9, so I'm closing this now. Let me know if you encounter any problems!

**Comment by Wulfsta** [comment]
Awesome, when I get some free time I'll set up NixOS again and try it out!
