### ISSUE TITLE
Update to 2.3.0

### ISSUE THREAD

**Issue by Wulfsta** [nixos-rocm/nixos-rocm#15]
I attempted to do this because I just got around to starting to [add PyTorch](https://github.com/nixos-rocm/nixos-rocm/issues/14), but noticed that llvm has been split into two packages and wasn't sure why.

**Comment by acowley** [comment]
I've pushed a [2.3.x branch](https://github.com/nixos-rocm/nixos-rocm/tree/2.3.x). I'm having trouble getting the usual tensorflow benchmarks to work, though, so I won't merge it just yet. TF with ROCm has often been pretty unstable for me, so there's reason to believe everything is working as expected. Let me know if you give it a try.

**Comment by Wulfsta** [comment]
When trying to build rocSPARSE for PyTorch, I ran into an issue with the version of HIP. It appears there's a patch being applied in pkgs/development/compilers/hip/default.nix that sets the flag -DHIP_VERSION_PATCH=18493. I wonder if this is now out of date?

**Comment by acowley** [comment]
It is out of date. I've pushed an update to the `2.3.x` branch.

**Comment by acowley** [comment]
I think this is good to go. I figured out how to get the tf benchmarks working on my memory-constrained system, and see a 4% speedup over ROCm 2.2 which is what I've read of elsewhere. I've merged the 2.3.x branch to master and updated the README.
