### ISSUE TITLE
hipCPU/hipsycl referenced in all-packages.nix

### ISSUE THREAD

**Issue by philroberts** [nixos-rocm/nixos-rocm#19]
On current master, I'm getting this:

`error: getting status of '/etc/nixos/overlays/nixos-rocm/pkgs/development/compilers/hipsycl/hipCPU.nix': No such file or directory`

when trying to run nix-env with nixos-rocm in my overlays.

Similarly if I comment out hipCPU and hipsycl from all-packages.nix:

`error: getting status of '/etc/nixos/overlays/nixos-rocm/pkgs/development/libraries/tensorflow/default.nix': No such file or directory`

**Comment by acowley** [comment]
Thank you for the report! I must have messed up a commit and included broken pieces, I’ll fix it this afternoon. You can comment out anything related to `hipsycl` and `tensorflow`.

**Comment by acowley** [comment]
Sorry for the trouble; this was sloppily done on my part.
