### ISSUE TITLE
nix-shell: "error: value is a function while a set was expected"

### ISSUE THREAD

**Issue by athas** [nixos-rocm/nixos-rocm#20]
This is similar to #18, although I'm pretty sure I've installed nixos-rocm correctly.

I am using the newest nixos-rocm in a local Git checkout.  I am also using an up-to-date nixpkgs unstable.  I have added nixos-rocm in my configuration.nix as follows:

```
  nixpkgs.overlays =
    [ (import /home/athas/repos/nixos-rocm ["gfx803" "gfx900" "gfx906"])
    ];
```

Whenever I try to run `nix-shell`, e.g. `nix-shell -p rocm-opencl-runtime --run ls`, I am told `error: value is a function while a set was expected`.  Interestingly, this happens also for other packages, e.g. `nix-shell -p curl` fails.  If I checkout 288bb21520f07d63ce8d7ff82942526beda7d761, then things seem to work (even without a `nixos-rebuild`!).

**Comment by kastaren** [comment]
How did you make it available to nix-shell? If you use ~/.config/nixpkgs/overlays.nix, don´t forget to put the full (import /home/athas/repos/nixos-rocm ["gfx803" "gfx900" "gfx906"]) in there too.

**Comment by athas** [comment]
The only place I have modified is my configuration.nix.  This used to work.  I also have a `~/.config/nixpkgs/overlays/rocm.nix` that is a symlink to `/home/athas/repos/nixos-rocm/default.nix`.  Should that be something different now?  I don't actually remember putting that file there, but I guess I must have...

**Comment by kastaren** [comment]
Doing it the way I just described doesn´t actually work, sorry (I hoped I deleted my comment in time). But I am quite sure this is the problem, nixos-rocm/default.nix needs the right arguments now. My sense the best way to do this is through ~/.config/nixpkgs/overlays.nix, but I need to check the syntax.

**Comment by acowley** [comment]
What I have in `overlays.nix` is 
```
[ (import ~/src/nixos-rocm/pkgs/all-packages.nix ["gfx803" "gfx900" "gfx906"])]
```

I think what you have should work, so perhaps I did something wrong in the `nixos-rocm/default.nix`.

**Comment by athas** [comment]
Things seem to work if I remove the `~/.config/nixpkgs/overlays` directory and just create a file `~/.config/nixpkgs/overlays.nix` with the contents

```
[ (import ~/src/nixos-rocm/pkgs/all-packages.nix ["gfx803" "gfx900" "gfx906"])]
```

This is good enough for me.  I don't know how parameterised overlays would work with the `overlays` directory, because I don't fully understand the overlay mechanism.

**Comment by acowley** [comment]
As for specifying your overlays, there may be some redundancy between you specifying `nixpkgs.overlays` and populating the `overlays` directory. I think (but I could be wrong), that your setting of `nixpkgs.overlays` takes precedence, so the `overlays` directory is not considered.

**Comment by acowley** [comment]
Ah, well I'm glad you were able to figure it out. I think you identified something here with the question about a parameterized overlay and the `overlays` directory. That should be mentioned in the README, so thank you for working it out.

**Comment by pl-semiotics** [comment]
@acowley Symlinking the overlays into place no longer works due to the parametrization that you have used (since the `default.nix` of the overlay now takes an extra parameter).  My understanding is that the normal way to solve this would be to look for settings in the nixpkgs configuration; have you considered using a mechanism like this that would not break the normal overlay import method (and which might be more conducive to upstreaming)?

**Comment by kastaren** [comment]
Yeah, the syntax from the people above is correct, I just missed putting mine in an actual list. I also struggled with this the other day, but adding a line to the readme would work for me.

**Comment by athas** [comment]
Yes, a line like "also put the following in `~/.config/nixpkgs/overlays.nix` in order for `nix-shell` to work" would have sufficed for me.

**Comment by acowley** [comment]
@peter-sa That sounds like the right approach. How does [this change](https://github.com/acowley/nixos-rocm/commit/b5dce92b82df4947a3e205c9b6769e2dedef1a6f) look to everyone?

**Comment by athas** [comment]
That looks great to me!  It also feels like the cleanest solution (in that other Nix packages do it the same way).
