### ISSUE TITLE
OpenCL image support 

### ISSUE THREAD

**Issue by DieGoldeneEnte** [nixos-rocm/nixos-rocm#31]
Darktable needs OpenCL image support, as a result I need to start it with `nix-shell -p rocr-ext` to use OpenCL.

How would I install the image support on my system so other programs can use it?

**Comment by acowley** [comment]
Maybe we should use a config option to make `rocr-ext` part of `propagatedBuildInputs` for `rocm-opencl-runtime`. Any downsides to that?

**Comment by DieGoldeneEnte** [comment]
I tried adding `propagatedBuildInputs = [ rocr-ext ];` to rocm-opencl-runtime.nix . But this doesn't make image support available. If I understand it correctly the environment variable `ROCR_EXT_DIR` is needed to make it available.

**Comment by acowley** [comment]
Recent changes steer users toward putting `rocm-runtime-ext` (the new name for `rocr-ext`) into `systemPackages`. It is [described](https://hydra.nixos.org/build/124487295/download/2/nixos/index.html#sec-gpu-accel-opencl-amd) in a new NixOS manual section.
