### ISSUE TITLE
How to do tests? (rocblas)

### ISSUE THREAD

**Issue by DieGoldeneEnte** [nixos-rocm/nixos-rocm#46]
I tried to run the tests on rocblas and noticed it doesn't work with doCheck set to true.
While fixing this I noticed it doesn't find the rocblas library since it is not in the path yet. What would be a good approach here?
I was thinking of separating the test into another derivation, but I know of no possibility to fail the original package based on the tests or how to run the tests automatically after building.

This also applies for other projects, for example compilers (I am thinking of hipsycl), since a different environment would be needed.

**Comment by acowley** [comment]
You need to add the build directory to the relevant paths. I think there are examples of this in nixpkgs, but I can’t think of a specific one.

Doing it as a separate derivation wouldn’t be useless, though. Whenever we get around to reporting CI status, that could include this sort of test.

**Comment by DieGoldeneEnte** [comment]
Thanks for the answer, I found some examples in nixpkgs (they are easy to find if you search for LD_LIBRARY_PATH).

For rocBLAS I decided on adding the test-binary to the derivation output, as it doesn't find the GPU from inside the sandbox (see #47)
