### ISSUE TITLE
Upstreaming libamdhip64.so.4

### ISSUE THREAD

**Issue by lovesegfault** [nixos-rocm/nixos-rocm#65]
I'm trying to package something that uses `libamdhip64.so.4`. I'm curious if it'd be possible to get the appropriate package into `nixpkgs`?

I'm happy to put in the work, as long as I understand what needs to be done.

Cheers!

**Comment by acowley** [comment]
I think `hip` can go into `nixpkgs` without much fuss given what’s already there. The main question mark is maintenance. I can not commit to the nixpkgs repo, and ROCm pieces are frequently updated, so I have opted to not take on that burden.

If you are up for it, then it should be a matter of adding `hip` to `all-packages`, and making sure to pass `llvmPackages_rocm` when calling it.

Something that would be valuable is having some automated tests to make sure it is working. The `hipcc` compiler is a somewhat complex script that relies on quite a number of paths and config files to work, so even when the `hip` package seems to build, the compiler may not work. I perform a minor manual verification every release with a test program. I check that the program builds, runs, and that it’s performance is as expected. 

We could either use an upstream test suite (assuming there is one), or script a test build ourselves. I’m not sure if we’d need a GPU in the test runner to have confidence that it’s working properly; that could be a problem if we really wanted those tests.

**Comment by lovesegfault** [comment]
> The main question mark is maintenance. I can not commit to the nixpkgs repo, and ROCm pieces are frequently updated, so I have opted to not take on that burden.

I can commit to nixpkgs and would be happy to fast-track and review any changes to ROCm infrastructure there.

**Comment by lovesegfault** [comment]
We did it! :partying_face:

**Comment by acowley** [comment]
Thank you!
