### ISSUE TITLE
Update to 1.9.0

### ISSUE THREAD

**Issue by ob7** [nixos-rocm/nixos-rocm#9]
I've tried doing it myself but editing the kernel file alone doesn't work.  Any ideas what I can do to get 1.9.0 working?

**Comment by acowley** [comment]
Did you try the [branch](https://github.com/nixos-rocm/nixos-rocm/tree/1.9.x)? I didn’t update the kernel as it’s not strictly necessary any more. We should update it, too, I suppose, just for completeness sake.

**Comment by ob7** [comment]
I didn't see that, thanks for pointing it out. I tried switching the kernel to 1.9 but had no luck.  I changed the 1.8.2 to 1.9.0 and updated the hash.  Wouldn't build though.  Anything else I need to update for that to work?

**Comment by acowley** [comment]
There shouldn't be any kernel parts with ROCm-1.9. Like it says [here](https://github.com/nixos-rocm/nixos-rocm/tree/1.9.x#installation), you can now use the mainline 4.18 kernel from nixpkgs, and then everything is user-space atop that. If that's what you're doing, can you say what specifically is failing?

**Comment by ob7** [comment]
Ohh nicee!!! Thanks for showing me that.

**Comment by acowley** [comment]
@ob7 Let me know if it's working for you and on what hardware. What I'd really like to do is push these things upstream into nixpkgs, but I'd like to know that things are working for everyone. If we could get hydra to build the various ROCm packages, we'd really have a nice GPU development setup.
